// Copyright (c) LASA Robotics and other contributors
// Open Source Software; you can modify and/or share it under the terms of
// the MIT license file in the root directory of this project.

package org.lasarobotics.hardware.ctre;

import org.lasarobotics.hardware.LoggableHardware;
import org.lasarobotics.hardware.PurpleManager;
import org.littletonrobotics.junction.AutoLog;
import org.littletonrobotics.junction.Logger;

import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.configs.CANcoderConfiguration;
import com.ctre.phoenix6.signals.SensorDirectionValue;

import edu.wpi.first.units.Units;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.MutAngle;
import edu.wpi.first.units.measure.MutAngularVelocity;

/** CTRE CANCoder */
public class CANCoder extends LoggableHardware {
  /** CANCoder ID */
  public static class ID {
    public final String name;
    public final PhoenixCANBus bus;
    public final int deviceID;

    /**
     * CANCoder ID
     * @param name Device name for logging
     * @param bus CAN bus device is connected to
     * @param deviceID CAN ID
     */
    public ID(String name, PhoenixCANBus bus, int deviceID) {
      this.name = name;
      this.bus = bus;
      this.deviceID = deviceID;
    }
  }

  /** CANCoder Status Frame */
  public enum CANCoderFrame {
    ABSOLUTE_POSITION,
    RELATIVE_POSITION,
    VELOCITY
  }

  @AutoLog
  public static class CANCoderInputs {
    public MutAngle absolutePosition = Units.Radians.zero().mutableCopy();
    public MutAngle relativePosition = Units.Radians.zero().mutableCopy();
    public MutAngularVelocity velocity = Units.RadiansPerSecond.zero().mutableCopy();
  }

  private com.ctre.phoenix6.hardware.CANcoder m_canCoder;

  private ID m_id;
  private CANCoderInputsAutoLogged m_inputs;

  public CANCoder(ID id) {
    this.m_id = id;
    this.m_canCoder = new com.ctre.phoenix6.hardware.CANcoder(m_id.deviceID, m_id.bus.name);
    this.m_inputs = new CANCoderInputsAutoLogged();

    // Update inputs on init
    periodic();

    // Register device with manager
    PurpleManager.add(this);
  }

   /**
     * Gets the absolute position of the sensor.
     * The absolute position may be unsigned (for example: [0,360) deg), or signed (for example: [-180,+180) deg). This is determined by a configuration. The default selection is unsigned.
     * The units are determined by the internal coefficient, default is rotations.
     * Note: this signal is not affected by calls to SetPosition().
     * @return The position of the sensor.
     */
  private Angle getAbsolutePosition() {
    return m_canCoder.getAbsolutePosition().getValue();
  }

  /**
   * Gets the position of the sensor.  This may be relative or absolute depending on configuration.
   * The units are determined by the internal coefficient, default is rotations.
   * @return The position of the sensor.
   */
  private Angle getRelativePosition() {
    return m_canCoder.getPosition().getValue();
  }

  /**
   * Gets the velocity of the sensor.
   * The units are determined by the internal coefficient, default is rotations per second.
   * @return The velocity of the sensor.
   */
  private AngularVelocity getVelocity() {
    return m_canCoder.getVelocity().getValue();
  }

  /**
   * Gets the velocity of the sensor.
   * The units are determined by the internal coefficient, default is rotations.
   * @return The Velocity of the sensor.
   */
  private void updateInputs() {
    m_inputs.absolutePosition.mut_replace(getAbsolutePosition());
    m_inputs.relativePosition.mut_replace(getRelativePosition());
    m_inputs.velocity.mut_replace(getVelocity());
  }

  /**
   * Call this method periodically
   */
  @Override
  protected void periodic() {
    updateInputs();
    Logger.processInputs(m_id.name, m_inputs);
  }

  /**
   * Get latest sensor input data
   * @return Latest sensor data
   */
  @Override
  public CANCoderInputsAutoLogged getInputs() {
    return m_inputs;
  }

  /**
   * Get device ID
   * @return Device ID
   */
  public ID getID() {
    return m_id;
  }

  /**
   * Sets the position of the sensor to specified value
   * The units are determined by the coefficient and unit-string configuration params, default is rotations.
   * @param position Position to reset to
   * @return StatusCode generated by function. 0 indicates no error.
   */
  public StatusCode resetPosition(double position) {
    return m_canCoder.setPosition(position);
  }

 /**
   * Sets the position of the sensor to zero
   * The units are determined by the coefficient and unit-string configuration params, default is degrees.
   * @return StatusCode generated by function. 0 indicates no error.
   */
  public StatusCode resetPosition() {
    return resetPosition(0.0);
  }

  /**
   * Configures all persistent settings to defaults (overloaded so timeoutMs is 50 ms).
   *
   * @return Status Code generated by function. 0 indicates no error.
   */
  public StatusCode configFactoryDefault() {
    return m_canCoder.getConfigurator().apply(new CANcoderConfiguration());
  }

  /**
   * Configures direction of the sensor to determine positive facing the LED side of the CANcoder.
   * @param direction The new sensor direction
   * @return StatusCode generated by function. 0 indicates no error.
   */
  public StatusCode configSensorDirection(SensorDirectionValue direction) {
    CANcoderConfiguration config = new CANcoderConfiguration();
    config.MagnetSensor.SensorDirection = direction;

    return m_canCoder.getConfigurator().apply(config);
  }

	/**
	 * Sets the period of the given status frame.
	 *
	 * @param statusFrame
	 *            Frame whose period is to be changed.
	 * @param frequencyHz
	 *            Frequency in Hz for the given frame.
	 * @return Status Code generated by function. 0 indicates no error.
	 */
  public StatusCode setStatusFramePeriod(CANCoderFrame statusFrame, int frequencyHz) {
    switch (statusFrame) {
      case ABSOLUTE_POSITION:
        return m_canCoder.getAbsolutePosition().setUpdateFrequency(frequencyHz);
      case RELATIVE_POSITION:
        return m_canCoder.getPosition().setUpdateFrequency(frequencyHz);
      case VELOCITY:
        return m_canCoder.getVelocity().setUpdateFrequency(frequencyHz);
      default:
        return StatusCode.OK;
    }
  }

  @Override
  public void close() {
    PurpleManager.remove(this);
    m_canCoder = null;
  }
}
